### ISSUE TITLE
访问/ui路径，返回的是空白页面

### ISSUE THREAD

**Issue by w198750** [UntaggedRui/clashindocker#1]
访问的就是这样的

![image](https://github.com/UntaggedRui/clashindocker/assets/58135554/c19bdd2b-3f78-41ab-b602-fc10759bca4b)

**Comment by UntaggedRui** [comment]
不好意思，git使用的不熟练，submodule没整明白。你更新一下最新代码 现在可以了。

**Comment by w198750** [comment]
可以了，非常感谢您提供这么好的开源项目
